<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Diagnosis_summary extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Diagnosis_summary_model');
    } 

    /*
     * Listing of diagnosis_summary
     */
    function index()
    {
        $data['diagnosis_summary'] = $this->Diagnosis_summary_model->get_all_diagnosis_summary();

        $data['_view'] = 'diagnosis_summary/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new diagnosis_summary
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('disease_date','Disease Date','required');
		$this->form_validation->set_rules('diagnosis_patron_code','Diagnosis Patron Code','required|integer');
		$this->form_validation->set_rules('diagnosis_comment','Diagnosis Comment','required');
		$this->form_validation->set_rules('diagnosis_physician_code','Diagnosis Physician Code','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'disease_date' => $this->input->post('disease_date'),
				'diagnosis_patron_code' => $this->input->post('diagnosis_patron_code'),
				'diagnosis_comment' => $this->input->post('diagnosis_comment'),
				'diagnosis_physician_code' => $this->input->post('diagnosis_physician_code'),
            );
            
            $diagnosis_summary_id = $this->Diagnosis_summary_model->add_diagnosis_summary($params);
            redirect('diagnosis_summary/index');
        }
        else
        {            
            $data['_view'] = 'diagnosis_summary/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a diagnosis_summary
     */
    function edit($diagnosis_reference_number)
    {   
        // check if the diagnosis_summary exists before trying to edit it
        $data['diagnosis_summary'] = $this->Diagnosis_summary_model->get_diagnosis_summary($diagnosis_reference_number);
        
        if(isset($data['diagnosis_summary']['diagnosis_reference_number']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('disease_date','Disease Date','required');
			$this->form_validation->set_rules('diagnosis_patron_code','Diagnosis Patron Code','required|integer');
			$this->form_validation->set_rules('diagnosis_comment','Diagnosis Comment','required');
			$this->form_validation->set_rules('diagnosis_physician_code','Diagnosis Physician Code','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'disease_date' => $this->input->post('disease_date'),
					'diagnosis_patron_code' => $this->input->post('diagnosis_patron_code'),
					'diagnosis_comment' => $this->input->post('diagnosis_comment'),
					'diagnosis_physician_code' => $this->input->post('diagnosis_physician_code'),
                );

                $this->Diagnosis_summary_model->update_diagnosis_summary($diagnosis_reference_number,$params);            
                redirect('diagnosis_summary/index');
            }
            else
            {
                $data['_view'] = 'diagnosis_summary/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The diagnosis_summary you are trying to edit does not exist.');
    } 

    /*
     * Deleting diagnosis_summary
     */
    function remove($diagnosis_reference_number)
    {
        $diagnosis_summary = $this->Diagnosis_summary_model->get_diagnosis_summary($diagnosis_reference_number);

        // check if the diagnosis_summary exists before trying to delete it
        if(isset($diagnosis_summary['diagnosis_reference_number']))
        {
            $this->Diagnosis_summary_model->delete_diagnosis_summary($diagnosis_reference_number);
            redirect('diagnosis_summary/index');
        }
        else
            show_error('The diagnosis_summary you are trying to delete does not exist.');
    }
    
}
