<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Diagnosis_symptom extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Diagnosis_symptom_model');
    } 

    /*
     * Listing of diagnosis_symptoms
     */
    function index()
    {
        $data['diagnosis_symptoms'] = $this->Diagnosis_symptom_model->get_all_diagnosis_symptoms();

        $data['_view'] = 'diagnosis_symptom/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new diagnosis_symptom
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $diagnosis_symptom_id = $this->Diagnosis_symptom_model->add_diagnosis_symptom($params);
            redirect('diagnosis_symptom/index');
        }
        else
        {            
            $data['_view'] = 'diagnosis_symptom/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a diagnosis_symptom
     */
    function edit($diagnosis_symptom_code)
    {   
        // check if the diagnosis_symptom exists before trying to edit it
        $data['diagnosis_symptom'] = $this->Diagnosis_symptom_model->get_diagnosis_symptom($diagnosis_symptom_code);
        
        if(isset($data['diagnosis_symptom']['diagnosis_symptom_code']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Diagnosis_symptom_model->update_diagnosis_symptom($diagnosis_symptom_code,$params);            
                redirect('diagnosis_symptom/index');
            }
            else
            {
                $data['_view'] = 'diagnosis_symptom/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The diagnosis_symptom you are trying to edit does not exist.');
    } 

    /*
     * Deleting diagnosis_symptom
     */
    function remove($diagnosis_symptom_code)
    {
        $diagnosis_symptom = $this->Diagnosis_symptom_model->get_diagnosis_symptom($diagnosis_symptom_code);

        // check if the diagnosis_symptom exists before trying to delete it
        if(isset($diagnosis_symptom['diagnosis_symptom_code']))
        {
            $this->Diagnosis_symptom_model->delete_diagnosis_symptom($diagnosis_symptom_code);
            redirect('diagnosis_symptom/index');
        }
        else
            show_error('The diagnosis_symptom you are trying to delete does not exist.');
    }
    
}
