<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Diagnosis_prescription extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Diagnosis_prescription_model');
    } 

    /*
     * Listing of diagnosis_prescriptions
     */
    function index()
    {
        $data['diagnosis_prescriptions'] = $this->Diagnosis_prescription_model->get_all_diagnosis_prescriptions();

        $data['_view'] = 'diagnosis_prescription/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new diagnosis_prescription
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'prescription_instructions' => $this->input->post('prescription_instructions'),
				'prescription_comment' => $this->input->post('prescription_comment'),
            );
            
            $diagnosis_prescription_id = $this->Diagnosis_prescription_model->add_diagnosis_prescription($params);
            redirect('diagnosis_prescription/index');
        }
        else
        {            
            $data['_view'] = 'diagnosis_prescription/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a diagnosis_prescription
     */
    function edit($diagnosis_reference_number)
    {   
        // check if the diagnosis_prescription exists before trying to edit it
        $data['diagnosis_prescription'] = $this->Diagnosis_prescription_model->get_diagnosis_prescription($diagnosis_reference_number);
        
        if(isset($data['diagnosis_prescription']['diagnosis_reference_number']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'prescription_instructions' => $this->input->post('prescription_instructions'),
					'prescription_comment' => $this->input->post('prescription_comment'),
                );

                $this->Diagnosis_prescription_model->update_diagnosis_prescription($diagnosis_reference_number,$params);            
                redirect('diagnosis_prescription/index');
            }
            else
            {
                $data['_view'] = 'diagnosis_prescription/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The diagnosis_prescription you are trying to edit does not exist.');
    } 

    /*
     * Deleting diagnosis_prescription
     */
    function remove($diagnosis_reference_number)
    {
        $diagnosis_prescription = $this->Diagnosis_prescription_model->get_diagnosis_prescription($diagnosis_reference_number);

        // check if the diagnosis_prescription exists before trying to delete it
        if(isset($diagnosis_prescription['diagnosis_reference_number']))
        {
            $this->Diagnosis_prescription_model->delete_diagnosis_prescription($diagnosis_reference_number);
            redirect('diagnosis_prescription/index');
        }
        else
            show_error('The diagnosis_prescription you are trying to delete does not exist.');
    }
    
}
