<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Disease_symptom_matrix extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Disease_symptom_matrix_model');
    } 

    /*
     * Listing of disease_symptom_matrix
     */
    function index()
    {
        $data['disease_symptom_matrix'] = $this->Disease_symptom_matrix_model->get_all_disease_symptom_matrix();

        $data['_view'] = 'disease_symptom_matrix/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new disease_symptom_matrix
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('disease_symptom_sequence','Disease Symptom Sequence','required|integer');
		$this->form_validation->set_rules('disease_symptom_rank','Disease Symptom Rank','required|integer');
		$this->form_validation->set_rules('disease_frequency','Disease Frequency','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'disease_symptom_sequence' => $this->input->post('disease_symptom_sequence'),
				'disease_symptom_rank' => $this->input->post('disease_symptom_rank'),
				'disease_frequency' => $this->input->post('disease_frequency'),
            );
            
            $disease_symptom_matrix_id = $this->Disease_symptom_matrix_model->add_disease_symptom_matrix($params);
            redirect('disease_symptom_matrix/index');
        }
        else
        {            
            $data['_view'] = 'disease_symptom_matrix/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a disease_symptom_matrix
     */
    function edit($disease_code)
    {   
        // check if the disease_symptom_matrix exists before trying to edit it
        $data['disease_symptom_matrix'] = $this->Disease_symptom_matrix_model->get_disease_symptom_matrix($disease_code);
        
        if(isset($data['disease_symptom_matrix']['disease_code']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('disease_symptom_sequence','Disease Symptom Sequence','required|integer');
			$this->form_validation->set_rules('disease_symptom_rank','Disease Symptom Rank','required|integer');
			$this->form_validation->set_rules('disease_frequency','Disease Frequency','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'disease_symptom_sequence' => $this->input->post('disease_symptom_sequence'),
					'disease_symptom_rank' => $this->input->post('disease_symptom_rank'),
					'disease_frequency' => $this->input->post('disease_frequency'),
                );

                $this->Disease_symptom_matrix_model->update_disease_symptom_matrix($disease_code,$params);            
                redirect('disease_symptom_matrix/index');
            }
            else
            {
                $data['_view'] = 'disease_symptom_matrix/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The disease_symptom_matrix you are trying to edit does not exist.');
    } 

    /*
     * Deleting disease_symptom_matrix
     */
    function remove($disease_code)
    {
        $disease_symptom_matrix = $this->Disease_symptom_matrix_model->get_disease_symptom_matrix($disease_code);

        // check if the disease_symptom_matrix exists before trying to delete it
        if(isset($disease_symptom_matrix['disease_code']))
        {
            $this->Disease_symptom_matrix_model->delete_disease_symptom_matrix($disease_code);
            redirect('disease_symptom_matrix/index');
        }
        else
            show_error('The disease_symptom_matrix you are trying to delete does not exist.');
    }
    
}
