<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Disease_category extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Disease_category_model');
    } 

    /*
     * Listing of disease_category
     */
    function index()
    {
        $data['disease_category'] = $this->Disease_category_model->get_all_disease_category();

        $data['_view'] = 'disease_category/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new disease_category
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('disease_category_name','Disease Category Name','required|max_length[30]');
		$this->form_validation->set_rules('disease_category_description','Disease Category Description','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'disease_category_name' => $this->input->post('disease_category_name'),
				'disease_category_description' => $this->input->post('disease_category_description'),
            );
            
            $disease_category_id = $this->Disease_category_model->add_disease_category($params);
            redirect('disease_category/index');
        }
        else
        {            
            $data['_view'] = 'disease_category/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a disease_category
     */
    function edit($disease_category_code)
    {   
        // check if the disease_category exists before trying to edit it
        $data['disease_category'] = $this->Disease_category_model->get_disease_category($disease_category_code);
        
        if(isset($data['disease_category']['disease_category_code']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('disease_category_name','Disease Category Name','required|max_length[30]');
			$this->form_validation->set_rules('disease_category_description','Disease Category Description','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'disease_category_name' => $this->input->post('disease_category_name'),
					'disease_category_description' => $this->input->post('disease_category_description'),
                );

                $this->Disease_category_model->update_disease_category($disease_category_code,$params);            
                redirect('disease_category/index');
            }
            else
            {
                $data['_view'] = 'disease_category/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The disease_category you are trying to edit does not exist.');
    } 

    /*
     * Deleting disease_category
     */
    function remove($disease_category_code)
    {
        $disease_category = $this->Disease_category_model->get_disease_category($disease_category_code);

        // check if the disease_category exists before trying to delete it
        if(isset($disease_category['disease_category_code']))
        {
            $this->Disease_category_model->delete_disease_category($disease_category_code);
            redirect('disease_category/index');
        }
        else
            show_error('The disease_category you are trying to delete does not exist.');
    }
    
}
