<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Disease_definition extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Disease_definition_model');
    } 

    /*
     * Listing of disease_definition
     */
    function index()
    {
        $data['disease_definition'] = $this->Disease_definition_model->get_all_disease_definition();
		$data['authLevel'] = 1;
        $this->load->view('templates/loginAuth', $data);
        $data['_view'] = 'disease_definition/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new disease_definition
     */
    function add()
    {   
        $this->load->library('form_validation');
		$data['authLevel'] = 1;
        $this->load->view('templates/loginAuth', $data);
		$this->form_validation->set_rules('disease_name','Disease Name','required|max_length[30]');
		$this->form_validation->set_rules('disease_description','Disease Description','required');
		$this->form_validation->set_rules('disease_category_code','Disease Category Code','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'disease_name' => $this->input->post('disease_name'),
				'disease_description' => $this->input->post('disease_description'),
				'disease_category_code' => $this->input->post('disease_category_code'),
            );
            
            $disease_definition_id = $this->Disease_definition_model->add_disease_definition($params);
            redirect('disease_definition/index');
        }
        else
        {            
            $data['_view'] = 'disease_definition/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a disease_definition
     */
    function edit($disease_code)
    {
		$data['authLevel'] = 1;
        $this->load->view('templates/loginAuth', $data);
        // check if the disease_definition exists before trying to edit it
        $data['disease_definition'] = $this->Disease_definition_model->get_disease_definition($disease_code);
        
        if(isset($data['disease_definition']['disease_code']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('disease_name','Disease Name','required|max_length[30]');
			$this->form_validation->set_rules('disease_description','Disease Description','required');
			$this->form_validation->set_rules('disease_category_code','Disease Category Code','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'disease_name' => $this->input->post('disease_name'),
					'disease_description' => $this->input->post('disease_description'),
					'disease_category_code' => $this->input->post('disease_category_code'),
                );

                $this->Disease_definition_model->update_disease_definition($disease_code,$params);            
                redirect('disease_definition/index');
            }
            else
            {
                $data['_view'] = 'disease_definition/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The disease_definition you are trying to edit does not exist.');
    } 

    /*
     * Deleting disease_definition
     */
    function remove($disease_code)
    {
		$data['authLevel'] = 1;
        $this->load->view('templates/loginAuth', $data);
        $disease_definition = $this->Disease_definition_model->get_disease_definition($disease_code);

        // check if the disease_definition exists before trying to delete it
        if(isset($disease_definition['disease_code']))
        {
            $this->Disease_definition_model->delete_disease_definition($disease_code);
            redirect('disease_definition/index');
        }
        else
            show_error('The disease_definition you are trying to delete does not exist.');
    }
    
}
