<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Disease_symptom extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Disease_symptom_model');
    } 

    /*
     * Listing of disease_symptoms
     */
    function index()
    {
        $data['disease_symptoms'] = $this->Disease_symptom_model->get_all_disease_symptoms();

        $data['_view'] = 'disease_symptom/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new disease_symptom
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('disease_symptom_name','Disease Symptom Name','required|max_length[30]');
		$this->form_validation->set_rules('disease_symptom_description','Disease Symptom Description','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'disease_symptom_name' => $this->input->post('disease_symptom_name'),
				'disease_symptom_description' => $this->input->post('disease_symptom_description'),
            );
            
            $disease_symptom_id = $this->Disease_symptom_model->add_disease_symptom($params);
            redirect('disease_symptom/index');
        }
        else
        {            
            $data['_view'] = 'disease_symptom/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a disease_symptom
     */
    function edit($disease_symptom_code)
    {   
        // check if the disease_symptom exists before trying to edit it
        $data['disease_symptom'] = $this->Disease_symptom_model->get_disease_symptom($disease_symptom_code);
        
        if(isset($data['disease_symptom']['disease_symptom_code']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('disease_symptom_name','Disease Symptom Name','required|max_length[30]');
			$this->form_validation->set_rules('disease_symptom_description','Disease Symptom Description','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'disease_symptom_name' => $this->input->post('disease_symptom_name'),
					'disease_symptom_description' => $this->input->post('disease_symptom_description'),
                );

                $this->Disease_symptom_model->update_disease_symptom($disease_symptom_code,$params);            
                redirect('disease_symptom/index');
            }
            else
            {
                $data['_view'] = 'disease_symptom/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The disease_symptom you are trying to edit does not exist.');
    } 

    /*
     * Deleting disease_symptom
     */
    function remove($disease_symptom_code)
    {
        $disease_symptom = $this->Disease_symptom_model->get_disease_symptom($disease_symptom_code);

        // check if the disease_symptom exists before trying to delete it
        if(isset($disease_symptom['disease_symptom_code']))
        {
            $this->Disease_symptom_model->delete_disease_symptom($disease_symptom_code);
            redirect('disease_symptom/index');
        }
        else
            show_error('The disease_symptom you are trying to delete does not exist.');
    }
    
}
