<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class State extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('State_model');
    } 

    /*
     * Listing of state
     */
    function index()
    {
        $data['state'] = $this->State_model->get_all_state();

        $data['_view'] = 'state/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new state
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('province_state_name','Province State Name','required|max_length[30]');
		$this->form_validation->set_rules('province_state_country_code','Province State Country Code','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'province_state_name' => $this->input->post('province_state_name'),
				'province_state_country_code' => $this->input->post('province_state_country_code'),
            );
            
            $state_id = $this->State_model->add_state($params);
            redirect('state/index');
        }
        else
        {            
            $data['_view'] = 'state/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a state
     */
    function edit($province_state_code)
    {   
        // check if the state exists before trying to edit it
        $data['state'] = $this->State_model->get_state($province_state_code);
        
        if(isset($data['state']['province_state_code']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('province_state_name','Province State Name','required|max_length[30]');
			$this->form_validation->set_rules('province_state_country_code','Province State Country Code','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'province_state_name' => $this->input->post('province_state_name'),
					'province_state_country_code' => $this->input->post('province_state_country_code'),
                );

                $this->State_model->update_state($province_state_code,$params);            
                redirect('state/index');
            }
            else
            {
                $data['_view'] = 'state/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The state you are trying to edit does not exist.');
    } 

    /*
     * Deleting state
     */
    function remove($province_state_code)
    {
        $state = $this->State_model->get_state($province_state_code);

        // check if the state exists before trying to delete it
        if(isset($state['province_state_code']))
        {
            $this->State_model->delete_state($province_state_code);
            redirect('state/index');
        }
        else
            show_error('The state you are trying to delete does not exist.');
    }
    
}
