<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Country_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get country by country_code
     */
    function get_country($country_code)
    {
        $country = $this->db->query("
            SELECT
                *

            FROM
                `country`

            WHERE
                `country_code` = ?
        ",array($country_code))->row_array();

        return $country;
    }
    
    /*
     * Get all countries
     */
    function get_all_countries()
    {
        $countries = $this->db->query("
            SELECT
                *

            FROM
                `country`

            WHERE
                1 = 1
        ")->result_array();

        return $countries;
    }
    
    /*
     * function to add new country
     */
    function add_country($params)
    {
        $this->db->insert('country',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update country
     */
    function update_country($country_code,$params)
    {
        $this->db->where('country_code',$country_code);
        $response = $this->db->update('country',$params);
        if($response)
        {
            return "country updated successfully";
        }
        else
        {
            return "Error occuring while updating country";
        }
    }
    
    /*
     * function to delete country
     */
    function delete_country($country_code)
    {
        $response = $this->db->delete('country',array('country_code'=>$country_code));
        if($response)
        {
            return "country deleted successfully";
        }
        else
        {
            return "Error occuring while deleting country";
        }
    }
}
