<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Diagnosis_prescription_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get diagnosis_prescription by diagnosis_reference_number
     */
    function get_diagnosis_prescription($diagnosis_reference_number)
    {
        $diagnosis_prescription = $this->db->query("
            SELECT
                *

            FROM
                `diagnosis_prescriptions`

            WHERE
                `diagnosis_reference_number` = ?
        ",array($diagnosis_reference_number))->row_array();

        return $diagnosis_prescription;
    }
    
    /*
     * Get all diagnosis_prescriptions
     */
    function get_all_diagnosis_prescriptions()
    {
        $diagnosis_prescriptions = $this->db->query("
            SELECT
                *

            FROM
                `diagnosis_prescriptions`

            WHERE
                1 = 1
        ")->result_array();

        return $diagnosis_prescriptions;
    }
    
    /*
     * function to add new diagnosis_prescription
     */
    function add_diagnosis_prescription($params)
    {
        $this->db->insert('diagnosis_prescriptions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update diagnosis_prescription
     */
    function update_diagnosis_prescription($diagnosis_reference_number,$params)
    {
        $this->db->where('diagnosis_reference_number',$diagnosis_reference_number);
        $response = $this->db->update('diagnosis_prescriptions',$params);
        if($response)
        {
            return "diagnosis_prescription updated successfully";
        }
        else
        {
            return "Error occuring while updating diagnosis_prescription";
        }
    }
    
    /*
     * function to delete diagnosis_prescription
     */
    function delete_diagnosis_prescription($diagnosis_reference_number)
    {
        $response = $this->db->delete('diagnosis_prescriptions',array('diagnosis_reference_number'=>$diagnosis_reference_number));
        if($response)
        {
            return "diagnosis_prescription deleted successfully";
        }
        else
        {
            return "Error occuring while deleting diagnosis_prescription";
        }
    }
}
