<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Diagnosis_summary_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get diagnosis_summary by diagnosis_reference_number
     */
    function get_diagnosis_summary($diagnosis_reference_number)
    {
        $diagnosis_summary = $this->db->query("
            SELECT
                *

            FROM
                `diagnosis_summary`

            WHERE
                `diagnosis_reference_number` = ?
        ",array($diagnosis_reference_number))->row_array();

        return $diagnosis_summary;
    }
    
    /*
     * Get all diagnosis_summary
     */
    function get_all_diagnosis_summary()
    {
        $diagnosis_summary = $this->db->query("
            SELECT
                *

            FROM
                `diagnosis_summary`

            WHERE
                1 = 1
        ")->result_array();

        return $diagnosis_summary;
    }
    
    /*
     * function to add new diagnosis_summary
     */
    function add_diagnosis_summary($params)
    {
        $this->db->insert('diagnosis_summary',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update diagnosis_summary
     */
    function update_diagnosis_summary($diagnosis_reference_number,$params)
    {
        $this->db->where('diagnosis_reference_number',$diagnosis_reference_number);
        $response = $this->db->update('diagnosis_summary',$params);
        if($response)
        {
            return "diagnosis_summary updated successfully";
        }
        else
        {
            return "Error occuring while updating diagnosis_summary";
        }
    }
    
    /*
     * function to delete diagnosis_summary
     */
    function delete_diagnosis_summary($diagnosis_reference_number)
    {
        $response = $this->db->delete('diagnosis_summary',array('diagnosis_reference_number'=>$diagnosis_reference_number));
        if($response)
        {
            return "diagnosis_summary deleted successfully";
        }
        else
        {
            return "Error occuring while deleting diagnosis_summary";
        }
    }
}
