<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Diagnosis_symptom_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get diagnosis_symptom by diagnosis_symptom_code
     */
    function get_diagnosis_symptom($diagnosis_symptom_code)
    {
        $diagnosis_symptom = $this->db->query("
            SELECT
                *

            FROM
                `diagnosis_symptoms`

            WHERE
                `diagnosis_symptom_code` = ?
        ",array($diagnosis_symptom_code))->row_array();

        return $diagnosis_symptom;
    }
    
    /*
     * Get all diagnosis_symptoms
     */
    function get_all_diagnosis_symptoms()
    {
        $diagnosis_symptoms = $this->db->query("
            SELECT
                *

            FROM
                `diagnosis_symptoms`

            WHERE
                1 = 1
        ")->result_array();

        return $diagnosis_symptoms;
    }
    
    /*
     * function to add new diagnosis_symptom
     */
    function add_diagnosis_symptom($params)
    {
        $this->db->insert('diagnosis_symptoms',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update diagnosis_symptom
     */
    function update_diagnosis_symptom($diagnosis_symptom_code,$params)
    {
        $this->db->where('diagnosis_symptom_code',$diagnosis_symptom_code);
        $response = $this->db->update('diagnosis_symptoms',$params);
        if($response)
        {
            return "diagnosis_symptom updated successfully";
        }
        else
        {
            return "Error occuring while updating diagnosis_symptom";
        }
    }
    
    /*
     * function to delete diagnosis_symptom
     */
    function delete_diagnosis_symptom($diagnosis_symptom_code)
    {
        $response = $this->db->delete('diagnosis_symptoms',array('diagnosis_symptom_code'=>$diagnosis_symptom_code));
        if($response)
        {
            return "diagnosis_symptom deleted successfully";
        }
        else
        {
            return "Error occuring while deleting diagnosis_symptom";
        }
    }
}
