<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Disease_diagnoses_summary_matrix_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get disease_diagnoses_summary_matrix by diagnosis_reference_number
     */
    function get_disease_diagnoses_summary_matrix($diagnosis_reference_number)
    {
        $disease_diagnoses_summary_matrix = $this->db->query("
            SELECT
                *

            FROM
                `disease_diagnoses_summary_matrix`

            WHERE
                `diagnosis_reference_number` = ?
        ",array($diagnosis_reference_number))->row_array();

        return $disease_diagnoses_summary_matrix;
    }
    
    /*
     * Get all disease_diagnoses_summary_matrix
     */
    function get_all_disease_diagnoses_summary_matrix()
    {
        $disease_diagnoses_summary_matrix = $this->db->query("
            SELECT
                *

            FROM
                `disease_diagnoses_summary_matrix`

            WHERE
                1 = 1
        ")->result_array();

        return $disease_diagnoses_summary_matrix;
    }
    
    /*
     * function to add new disease_diagnoses_summary_matrix
     */
    function add_disease_diagnoses_summary_matrix($params)
    {
        $this->db->insert('disease_diagnoses_summary_matrix',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update disease_diagnoses_summary_matrix
     */
    function update_disease_diagnoses_summary_matrix($diagnosis_reference_number,$params)
    {
        $this->db->where('diagnosis_reference_number',$diagnosis_reference_number);
        $response = $this->db->update('disease_diagnoses_summary_matrix',$params);
        if($response)
        {
            return "disease_diagnoses_summary_matrix updated successfully";
        }
        else
        {
            return "Error occuring while updating disease_diagnoses_summary_matrix";
        }
    }
    
    /*
     * function to delete disease_diagnoses_summary_matrix
     */
    function delete_disease_diagnoses_summary_matrix($diagnosis_reference_number)
    {
        $response = $this->db->delete('disease_diagnoses_summary_matrix',array('diagnosis_reference_number'=>$diagnosis_reference_number));
        if($response)
        {
            return "disease_diagnoses_summary_matrix deleted successfully";
        }
        else
        {
            return "Error occuring while deleting disease_diagnoses_summary_matrix";
        }
    }
}
