<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Disease_symptom_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get disease_symptom by disease_symptom_code
     */
    function get_disease_symptom($disease_symptom_code)
    {
        $disease_symptom = $this->db->query("
            SELECT
                *

            FROM
                `disease_symptoms`

            WHERE
                `disease_symptom_code` = ?
        ",array($disease_symptom_code))->row_array();

        return $disease_symptom;
    }
    
    /*
     * Get all disease_symptoms
     */
    function get_all_disease_symptoms()
    {
        $disease_symptoms = $this->db->query("
            SELECT
                *

            FROM
                `disease_symptoms`

            WHERE
                1 = 1
        ")->result_array();

        return $disease_symptoms;
    }
    
    /*
     * function to add new disease_symptom
     */
    function add_disease_symptom($params)
    {
        $this->db->insert('disease_symptoms',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update disease_symptom
     */
    function update_disease_symptom($disease_symptom_code,$params)
    {
        $this->db->where('disease_symptom_code',$disease_symptom_code);
        $response = $this->db->update('disease_symptoms',$params);
        if($response)
        {
            return "disease_symptom updated successfully";
        }
        else
        {
            return "Error occuring while updating disease_symptom";
        }
    }
    
    /*
     * function to delete disease_symptom
     */
    function delete_disease_symptom($disease_symptom_code)
    {
        $response = $this->db->delete('disease_symptoms',array('disease_symptom_code'=>$disease_symptom_code));
        if($response)
        {
            return "disease_symptom deleted successfully";
        }
        else
        {
            return "Error occuring while deleting disease_symptom";
        }
    }
}
