<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Disease_definition_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get disease_definition by disease_code
     */
    function get_disease_definition($disease_code)
    {
        $disease_definition = $this->db->query("
            SELECT
                *

            FROM
                `disease_definition`

            WHERE
                `disease_code` = ?
        ",array($disease_code))->row_array();

        return $disease_definition;
    }
    
    /*
     * Get all disease_definition
     */
    function get_all_disease_definition()
    {
        $disease_definition = $this->db->query("
            SELECT
                *

            FROM
                `disease_definition`

            WHERE
                1 = 1
        ")->result_array();

        return $disease_definition;
    }
    
    /*
     * function to add new disease_definition
     */
    function add_disease_definition($params)
    {
        $this->db->insert('disease_definition',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update disease_definition
     */
    function update_disease_definition($disease_code,$params)
    {
        $this->db->where('disease_code',$disease_code);
        $response = $this->db->update('disease_definition',$params);
        if($response)
        {
            return "disease_definition updated successfully";
        }
        else
        {
            return "Error occuring while updating disease_definition";
        }
    }
    
    /*
     * function to delete disease_definition
     */
    function delete_disease_definition($disease_code)
    {
        $response = $this->db->delete('disease_definition',array('disease_code'=>$disease_code));
        if($response)
        {
            return "disease_definition deleted successfully";
        }
        else
        {
            return "Error occuring while deleting disease_definition";
        }
    }
}
