<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Physician_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get physician by physician_code
     */
    function get_physician($physician_code)
    {
        $physician = $this->db->query("
            SELECT
                *

            FROM
                `physicians`

            WHERE
                `physician_code` = ?
        ",array($physician_code))->row_array();

        return $physician;
    }
    
    /*
     * Get all physicians
     */
    function get_all_physicians()
    {
        $physicians = $this->db->query("
            SELECT
                *

            FROM
                `physicians`

            WHERE
                1 = 1
        ")->result_array();

        return $physicians;
    }
    
    /*
     * function to add new physician
     */
    function add_physician($params)
    {
        $this->db->insert('physicians',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update physician
     */
    function update_physician($physician_code,$params)
    {
        $this->db->where('physician_code',$physician_code);
        $response = $this->db->update('physicians',$params);
        if($response)
        {
            return "physician updated successfully";
        }
        else
        {
            return "Error occuring while updating physician";
        }
    }
    
    /*
     * function to delete physician
     */
    function delete_physician($physician_code)
    {
        $response = $this->db->delete('physicians',array('physician_code'=>$physician_code));
        if($response)
        {
            return "physician deleted successfully";
        }
        else
        {
            return "Error occuring while deleting physician";
        }
    }
}
