<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class State_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get state by province_state_code
     */
    function get_state($province_state_code)
    {
        $state = $this->db->query("
            SELECT
                *

            FROM
                `state`

            WHERE
                `province_state_code` = ?
        ",array($province_state_code))->row_array();

        return $state;
    }
    
    /*
     * Get all state
     */
    function get_all_state()
    {
        $state = $this->db->query("
            SELECT
                *

            FROM
                `state`

            WHERE
                1 = 1
        ")->result_array();

        return $state;
    }
    
    /*
     * function to add new state
     */
    function add_state($params)
    {
        $this->db->insert('state',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update state
     */
    function update_state($province_state_code,$params)
    {
        $this->db->where('province_state_code',$province_state_code);
        $response = $this->db->update('state',$params);
        if($response)
        {
            return "state updated successfully";
        }
        else
        {
            return "Error occuring while updating state";
        }
    }
    
    /*
     * function to delete state
     */
    function delete_state($province_state_code)
    {
        $response = $this->db->delete('state',array('province_state_code'=>$province_state_code));
        if($response)
        {
            return "state deleted successfully";
        }
        else
        {
            return "Error occuring while deleting state";
        }
    }
}
