<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Visiting_patron_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get visiting_patron by patron_code
     */
    function get_visiting_patron($patron_code)
    {
        $visiting_patron = $this->db->query("
            SELECT
                *

            FROM
                `visiting_patron`

            WHERE
                `patron_code` = ?
        ",array($patron_code))->row_array();

        return $visiting_patron;
    }
    
    /*
     * Get all visiting_patron
     */
    function get_all_visiting_patron()
    {
        $visiting_patron = $this->db->query("
            SELECT
                *

            FROM
                `visiting_patron`

            WHERE
                1 = 1
        ")->result_array();

        return $visiting_patron;
    }
    
    /*
     * function to add new visiting_patron
     */
    function add_visiting_patron($params)
    {
        $this->db->insert('visiting_patron',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update visiting_patron
     */
    function update_visiting_patron($patron_code,$params)
    {
        $this->db->where('patron_code',$patron_code);
        $response = $this->db->update('visiting_patron',$params);
        if($response)
        {
            return "visiting_patron updated successfully";
        }
        else
        {
            return "Error occuring while updating visiting_patron";
        }
    }
    
    /*
     * function to delete visiting_patron
     */
    function delete_visiting_patron($patron_code)
    {
        $response = $this->db->delete('visiting_patron',array('patron_code'=>$patron_code));
        if($response)
        {
            return "visiting_patron deleted successfully";
        }
        else
        {
            return "Error occuring while deleting visiting_patron";
        }
    }
}
